#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Fix Vietnamese diacritics in vocabulary file"""

import json
import re

# Mapping of Vietnamese words without diacritics to proper form
# This is a comprehensive mapping based on the vocabulary context
VIETNAMESE_MAPPING = {
    # Topic names
    "Gia dinh": "Gia đình",
    "Dong vat": "Động vật",
    "Bo phan co the": "Bộ phận cơ thể",
    "Kinh doanh": "Kinh doanh",
    "Cam xuc": "Cảm xúc",
    "Tinh cach": "Tính cách",
    "Tinh tu": "Tính từ",
    "Dong tu": "Động từ",
    "Thoi gian": "Thời gian",
    "Do an": "Đồ ăn",
    "Nha cua": "Nhà cửa",
    "Giao thong": "Giao thông",
    "Quan ao": "Quần áo",
    "Mau sac": "Màu sắc",
    "So dem": "Số đếm",
    "Suc khoe": "Sức khỏe",
    "Truong hoc": "Trường học",
    "Thoi tiet": "Thời tiết",
    "Sinh hoat hang ngay": "Sinh hoạt hàng ngày",
    "Mua sam": "Mua sắm",
    "The thao": "Thể thao",
    "Cong nghe": "Công nghệ",
    "Thien nhien": "Thiên nhiên",
    "Nghe nghiep": "Nghề nghiệp",
    "So thich": "Sở thích",
    "Du lich": "Du lịch",
    "Nha hang": "Nhà hàng",
    "Dong tu + gioi tu": "Động từ + giới từ",
    "Cum danh tu - dong tu": "Cụm danh từ - động từ",
    
    # Family (note: context matters, "bo" means father, not butter)
    "bo": "bố",
    "me": "mẹ",
    "bo me": "bố mẹ",
    "dua tre": "đứa trẻ",
    "con trai": "con trai",
    "con gai": "con gái",
    "anh/em trai": "anh/em trai",
    "chi/em gai": "chị/em gái",
    "ba noi/ngoai": "bà nội/ngoại",
    "ong noi/ngoai": "ông nội/ngoại",
    "ong": "ông",
    "ba": "bà",
    "chau": "cháu",
    "chau trai": "cháu trai",
    "chau gai": "cháu gái",
    "chu/bac/cau": "chú/bác/cậu",
    "co/di/mo": "cô/dì/mợ",
    "anh/em ho (nam)": "anh/em họ (nam)",
    "chi/em ho (nu)": "chị/em họ (nữ)",
    "hon phu": "hôn phu",
    "hon the": "hôn thê",
    "vo": "vợ",
    "chong": "chồng",
    "bo chong/vo": "bố chồng/vợ",
    "me chong/vo": "mẹ chồng/vợ",
    "con re": "con rể",
    "con dau": "con dâu",
    "anh/em re": "anh/em rể",
    "chi/em dau": "chị/em dâu",
    "gia dinh": "gia đình",
    "ba": "bà",
    
    # Animals
    "con meo": "con mèo",
    "con cho": "con chó",
    "con ngua": "con ngựa",
    "con lon": "con lợn",
    "con bo": "con bò",
    "con cuu": "con cừu",
    "con de": "con dê",
    "con ga trong": "con gà trống",
    "con ga": "con gà",
    "con vit": "con vịt",
    "con ngong": "con ngỗng",
    "con chim": "con chim",
    "con ca": "con cá",
    "con tho": "con thỏ",
    "chuot hamster": "chuột hamster",
    "con chuot": "con chuột",
    "con chuot cong": "con chuột cống",
    "con voi": "con voi",
    "con su tu": "con sư tử",
    "con ho": "con hổ",
    "con gau": "con gấu",
    "gau bac cuc": "gấu bắc cực",
    "con soi": "con sói",
    "con cao": "con cáo",
    "con khi": "con khỉ",
    "huou cao co": "hươu cao cổ",
    "ngua van": "ngựa vằn",
    "te giac": "tê giác",
    "ha ma": "hà mã",
    "ca sau": "cá sấu",
    "con ran": "con rắn",
    "con rua": "con rùa",
    "con ech": "con ếch",
    "ca heo": "cá heo",
    "ca voi": "cá voi",
    "ca map": "cá mập",
    "dai bang": "đại bàng",
    "con cu": "con cú",
    "con vet": "con vẹt",
    "thien nga": "thiên nga",
    "chim bo cau": "chim bồ câu",
    "con nhen": "con nhện",
    "bo canh cung": "bọ cánh cứng",
    "nhim": "nhím",
    "con soc": "con sóc",
    "con huou": "con hươu",
    "con lua": "con lừa",
    "lac da": "lạc đà",
    "chim canh cut": "chim cánh cụt",
    "con doi": "con dơi",
    "con sua": "con sứa",
    "con tom": "con tôm",
    "con cua": "con cua",
    "con lun": "con lửng",
    "bo cap": "bọ cạp",
    "thu cung": "thú cưng",
    "dong vat": "động vật",
    
    # Body parts
    "dau": "đầu",
    "mat/khuon mat": "mặt/khuôn mặt",
    "toc": "tóc",
    "mat": "mắt",
    "tai": "tai",
    "mui": "mũi",
    "mieng": "miệng",
    "moi": "môi",
    "rang": "răng",
    "luoi": "lưỡi",
    "cam": "cằm",
    "ma": "má",
    "tran": "trán",
    "long may": "lông mày",
    "long mi": "lông mi",
    "co": "cổ",
    "vai": "vai",
    "nguc": "ngực",
    "lung": "lưng",
    "bung": "bụng",
    "hong": "hông",
    "canh tay": "cánh tay",
    "khuyu tay": "khuỷu tay",
    "co tay": "cổ tay",
    "ban tay": "bàn tay",
    "ngon tay": "ngón tay",
    "ngon cai": "ngón cái",
    "mong tay": "móng tay",
    "chan": "chân",
    "dui": "đùi",
    "dau goi": "đầu gối",
    "bap chan": "bắp chân",
    "mat ca chan": "mắt cá chân",
    "ban chan": "bàn chân",
    "ngon chan": "ngón chân",
    "got chan": "gót chân",
    "da": "da",
    "xuong": "xương",
    "co bap": "cơ bắp",
    "mau/huyet": "máu/huyết",
    "tim": "tim",
    "phoi": "phổi",
    "gan": "gan",
    "da day": "dạ dày",
    "ruot": "ruột",
    "than": "thận",
    "nao": "não",
    "co the": "cơ thể",
    "cam": "cằm",
    "day than kinh": "dây thần kinh",
    "tinh mach": "tĩnh mạch",
    "dong mach": "động mạch",
    "khop xuong": "khớp xương",
    "co hoang": "cơ hoành",
    "man nhan": "màng nhĩ",
    "von mat": "võng mạc",
    "giap trang": "giáp trạng",
    "tuy song": "tủy sống",
    
    # Business
    "cong ty": "công ty",
    "doanh nghiep": "doanh nghiệp",
    "van phong": "văn phòng",
    "sep": "sếp",
    "nhan vien": "nhân viên",
    "dong nghiep": "đồng nghiệp",
    "khach hang": "khách hàng",
    "doi tac": "đối tác",
    "hop dong": "hợp đồng",
    "du an": "dự án",
    "cuoc hop": "cuộc họp",
    "bao cao": "báo cáo",
    "ke hoach": "kế hoạch",
    "muc tieu": "mục tiêu",
    "ngan sach": "ngân sách",
    "doanh thu": "doanh thu",
    "loi nhuan": "lợi nhuận",
    "chi phi": "chi phí",
    "dau tu": "đầu tư",
    "co phieu": "cổ phiếu",
    "thi truong": "thị trường",
    "canh tranh": "cạnh tranh",
    "chien luoc": "chiến lược",
    "san pham": "sản phẩm",
    "dich vu": "dịch vụ",
    "chat luong": "chất lượng",
    "gia ca": "giá cả",
    "khuyen mai": "khuyến mãi",
    "quang cao": "quảng cáo",
    "thuong hieu": "thương hiệu",
    "ban hang": "bán hàng",
    "mua hang": "mua hàng",
    "don hang": "đơn hàng",
    "giao hang": "giao hàng",
    "hoa don": "hóa đơn",
    "thanh toan": "thanh toán",
    "tien mat": "tiền mặt",
    "chuyen khoan": "chuyển khoản",
    "the tin dung": "thẻ tín dụng",
    "ngan hang": "ngân hàng",
    "tai khoan": "tài khoản",
    "vay": "vay",
    "lai suat": "lãi suất",
    "thue": "thuế",
    "luong": "lương",
    "thuong": "thưởng",
    "tang luong": "tăng lương",
    "nghi phep": "nghỉ phép",
    "sa thai": "sa thải",
    "tuyen dung": "tuyển dụng",
    "phong van": "phỏng vấn",
    "kinh doanh": "kinh doanh",
    "tien": "tiền",
    "nha tuyen dung": "nhà tuyển dụng",
    "ban lam viec": "bàn làm việc",
    "bo vest": "bộ vest",
    "su nghiep": "sự nghiệp",
    "cong nhan": "công nhân",
    "khoan vay": "khoản vay",
    "phong bi": "phong bì",
    "bao hiem": "bảo hiểm",
    "cong nghiep": "công nghiệp",
    "cuoc hen": "cuộc hẹn",
    "thua lo": "thua lỗ",
    "gia tri": "giá trị",
    "don xin viec": "đơn xin việc",
    "tien te": "tiền tệ",
    "so yeu ly lich": "sơ yếu lý lịch",
    "tang truong": "tăng trưởng",
    "nhan hieu": "nhãn hiệu",
    "phan phoi": "phân phối",
    "van chuyen": "vận chuyển",
    "xuat khau": "xuất khẩu",
    "nhap khau": "nhập khẩu",
    "co phan": "cổ phần",
    "von": "vốn",
    "lai": "lãi",
    "lo": "lỗ",
    "no": "nợ",
    "ky han": "kỳ hạn",
    "hop dong lao dong": "hợp đồng lao động",
    "nghi huu": "nghỉ hưu",
    "hoi nghi": "hội nghị",
    "thuong luong": "thương lượng",
    "dam phan": "đàm phán",
    
    # Feelings/Emotions
    "vui": "vui",
    "buon": "buồn",
    "gian/tuc gian": "giận/tức giận",
    "so hai": "sợ hãi",
    "lo lang": "lo lắng",
    "hanh phuc": "hạnh phúc",
    "yeu": "yêu",
    "ghet": "ghét",
    "ngac nhien": "ngạc nhiên",
    "that vong": "thất vọng",
    "chan": "chán",
    "thu vi": "thú vị",
    "hao hung": "hào hứng",
    "tu hao": "tự hào",
    "xau ho": "xấu hổ",
    "ghen ti": "ghen tị",
    "co don": "cô đơn",
    "met moi": "mệt mỏi",
    "thoai mai": "thoải mái",
    "cang thang": "căng thẳng",
    "binh tinh": "bình tĩnh",
    "hoang mang": "hoang mang",
    "hy vong": "hy vọng",
    "tuyet vong": "tuyệt vọng",
    "cam xuc": "cảm xúc",
    "tam trang": "tâm trạng",
    "cam giac": "cảm giác",
    "vui ve": "vui vẻ",
    "buon ba": "buồn bã",
    "buc boi": "bực bội",
    "hoi hop": "hồi hộp",
    "so": "sợ",
    "nho": "nhớ",
    "thuong": "thương",
    "ghen": "ghen",
    "tuc": "tức",
    
    # Character/Personality
    "tot bung": "tốt bụng",
    "than thien": "thân thiện",
    "vui tinh": "vui tính",
    "nghiem tuc": "nghiêm túc",
    "cham chi": "chăm chỉ",
    "luoi bieng": "lười biếng",
    "thong minh": "thông minh",
    "ngu ngoc": "ngu ngốc",
    "dung cam": "dũng cảm",
    "nhat gan": "nhát gan",
    "trung thuc": "trung thực",
    "gian doi": "gian dối",
    "kien nhan": "kiên nhẫn",
    "nong nay": "nóng nảy",
    "hao phong": "hào phóng",
    "keo kiet": "keo kiệt",
    "khiem ton": "khiêm tốn",
    "kieu ngao": "kiêu ngạo",
    "lich su": "lịch sự",
    "tho lo": "thô lỗ",
    "tu tin": "tự tin",
    "e de": "e dè",
    "lac quan": "lạc quan",
    "bi quan": "bi quan",
    "sang tao": "sáng tạo",
    "can than": "cẩn thận",
    "bat can": "bất cẩn",
    "trach nhiem": "trách nhiệm",
    "vo trach nhiem": "vô trách nhiệm",
    "tinh cach": "tính cách",
    "dac diem": "đặc điểm",
    "nhan cach": "nhân cách",
    
    # Adjectives
    "tot": "tốt",
    "xau": "xấu",
    "lon": "lớn",
    "nho": "nhỏ",
    "cao": "cao",
    "thap": "thấp",
    "dai": "dài",
    "ngan": "ngắn",
    "rong": "rộng",
    "hep": "hẹp",
    "nang": "nặng",
    "nhe": "nhẹ",
    "nhanh": "nhanh",
    "cham": "chậm",
    "moi": "mới",
    "cu": "cũ",
    "tre": "trẻ",
    "gia": "già",
    "nong": "nóng",
    "lanh": "lạnh",
    "am": "ấm",
    "mat": "mát",
    "kho": "khô",
    "uot": "ướt",
    "sach": "sạch",
    "ban": "bẩn",
    "dep": "đẹp",
    "xau xi": "xấu xí",
    "ngon": "ngon",
    "do": "dở",
    "de": "dễ",
    "kho khan": "khó khăn",
    "don gian": "đơn giản",
    "phuc tap": "phức tạp",
    "quan trong": "quan trọng",
    "binh thuong": "bình thường",
    "dac biet": "đặc biệt",
    "giong nhau": "giống nhau",
    "khac nhau": "khác nhau",
    "day": "đầy",
    "trong": "trống",
    "sang": "sáng",
    "toi": "tối",
    "ro rang": "rõ ràng",
    "mo ho": "mơ hồ",
    "dung": "đúng",
    "sai": "sai",
    "that": "thật",
    "gia": "giả",
    "tu do": "tự do",
    "an toan": "an toàn",
    "nguy hiem": "nguy hiểm",
    "can thiet": "cần thiết",
    "kha thi": "khả thi",
    "co the": "có thể",
    "bat kha thi": "bất khả thi",
    "hoan hao": "hoàn hảo",
    "tuyet voi": "tuyệt vời",
    "kinh khung": "kinh khủng",
    "te hai": "tệ hại",
    
    # Verbs
    "la": "là",
    "co": "có",
    "lam": "làm",
    "di": "đi",
    "den": "đến",
    "ve": "về",
    "an": "ăn",
    "uong": "uống",
    "ngu": "ngủ",
    "day": "dậy",
    "noi": "nói",
    "nghe": "nghe",
    "doc": "đọc",
    "viet": "viết",
    "hoc": "học",
    "day": "dạy",
    "hieu": "hiểu",
    "biet": "biết",
    "nghi": "nghĩ",
    "nho": "nhớ",
    "quen": "quên",
    "tim": "tìm",
    "thay": "thấy",
    "nhin": "nhìn",
    "xem": "xem",
    "choi": "chơi",
    "lam viec": "làm việc",
    "nghi ngoi": "nghỉ ngơi",
    "cho": "chờ",
    "doi": "đợi",
    "mua": "mua",
    "ban": "bán",
    "tra": "trả",
    "cho": "cho",
    "nhan": "nhận",
    "gui": "gửi",
    "lay": "lấy",
    "de": "để",
    "dat": "đặt",
    "mo": "mở",
    "dong": "đóng",
    "bat": "bật",
    "tat": "tắt",
    "bat dau": "bắt đầu",
    "ket thuc": "kết thúc",
    "tiep tuc": "tiếp tục",
    "dung lai": "dừng lại",
    "thay doi": "thay đổi",
    "giu nguyen": "giữ nguyên",
    "tang": "tăng",
    "giam": "giảm",
    "phat trien": "phát triển",
    "cai thien": "cải thiện",
    "giup do": "giúp đỡ",
    "yeu cau": "yêu cầu",
    "de nghi": "đề nghị",
    "dong y": "đồng ý",
    "tu choi": "từ chối",
    "chap nhan": "chấp nhận",
    "quyet dinh": "quyết định",
    "lua chon": "lựa chọn",
    "so sanh": "so sánh",
    "kiem tra": "kiểm tra",
    "danh gia": "đánh giá",
    "giai thich": "giải thích",
    "hoi": "hỏi",
    "tra loi": "trả lời",
    "gioi thieu": "giới thiệu",
    "hen gap": "hẹn gặp",
    "gap": "gặp",
    "chia tay": "chia tay",
    "yeu thuong": "yêu thương",
    "ghet bo": "ghét bỏ",
    "cam on": "cảm ơn",
    "xin loi": "xin lỗi",
    "chuc mung": "chúc mừng",
    
    # Time
    "giay": "giây",
    "phut": "phút",
    "gio": "giờ",
    "ngay": "ngày",
    "tuan": "tuần",
    "thang": "tháng",
    "nam": "năm",
    "the ky": "thế kỷ",
    "sang": "sáng",
    "trua": "trưa",
    "chieu": "chiều",
    "toi": "tối",
    "dem": "đêm",
    "hom nay": "hôm nay",
    "hom qua": "hôm qua",
    "ngay mai": "ngày mai",
    "tuan nay": "tuần này",
    "tuan truoc": "tuần trước",
    "tuan sau": "tuần sau",
    "thang nay": "tháng này",
    "thang truoc": "tháng trước",
    "thang sau": "tháng sau",
    "nam nay": "năm nay",
    "nam ngoai": "năm ngoái",
    "nam sau": "năm sau",
    "thu hai": "thứ hai",
    "thu ba": "thứ ba",
    "thu tu": "thứ tư",
    "thu nam": "thứ năm",
    "thu sau": "thứ sáu",
    "thu bay": "thứ bảy",
    "chu nhat": "chủ nhật",
    "cuoi tuan": "cuối tuần",
    "ngay nghi": "ngày nghỉ",
    "ngay le": "ngày lễ",
    "ky nghi": "kỳ nghỉ",
    "som": "sớm",
    "muon": "muộn",
    "dung gio": "đúng giờ",
    "truoc": "trước",
    "sau": "sau",
    "bay gio": "bây giờ",
    "luc nay": "lúc này",
    "khi nao": "khi nào",
    "bao lau": "bao lâu",
    "thuong xuyen": "thường xuyên",
    "doi khi": "đôi khi",
    "hiem khi": "hiếm khi",
    "luon luon": "luôn luôn",
    "khong bao gio": "không bao giờ",
    "thoi gian": "thời gian",
    
    # Food
    "com": "cơm",
    "banh mi": "bánh mì",
    "mi": "mì",
    "pho": "phở",
    "bun": "bún",
    "chao": "cháo",
    "xoi": "xôi",
    "thit": "thịt",
    "thit bo": "thịt bò",
    "thit lon": "thịt lợn",
    "thit ga": "thịt gà",
    "ca": "cá",
    "tom": "tôm",
    "cua": "cua",
    "muc": "mực",
    "trung": "trứng",
    "sua": "sữa",
    "pho mai": "phô mai",
    "dau": "dầu",
    "muoi": "muối",
    "duong": "đường",
    "tieu": "tiêu",
    "ot": "ớt",
    "hanh": "hành",
    "toi": "tỏi",
    "gung": "gừng",
    "rau": "rau",
    "ca chua": "cà chua",
    "khoai tay": "khoai tây",
    "ca rot": "cà rốt",
    "bap cai": "bắp cải",
    "dua chuot": "dưa chuột",
    "bi": "bí",
    "dau": "đậu",
    "nam": "nấm",
    "trai cay": "trái cây",
    "tao": "táo",
    "cam": "cam",
    "chuoi": "chuối",
    "nho": "nho",
    "dua hau": "dưa hấu",
    "xoai": "xoài",
    "dua": "dừa",
    "dau tay": "dâu tây",
    "le": "lê",
    "dao": "đào",
    "nuoc": "nước",
    "nuoc ep": "nước ép",
    "tra": "trà",
    "ca phe": "cà phê",
    "bia": "bia",
    "ruou": "rượu",
    "banh": "bánh",
    "banh ngot": "bánh ngọt",
    "kem": "kem",
    "keo": "kẹo",
    "socola": "sô cô la",
    "do an": "đồ ăn",
    "bua an": "bữa ăn",
    "bua sang": "bữa sáng",
    "bua trua": "bữa trưa",
    "bua toi": "bữa tối",
    "mon an": "món ăn",
    "do uong": "đồ uống",
    "thuc don": "thực đơn",
    "cong thuc": "công thức",
    "nau an": "nấu ăn",
    
    # House
    "nha": "nhà",
    "can ho": "căn hộ",
    "phong": "phòng",
    "phong khach": "phòng khách",
    "phong ngu": "phòng ngủ",
    "phong bep": "phòng bếp",
    "phong tam": "phòng tắm",
    "phong an": "phòng ăn",
    "phong lam viec": "phòng làm việc",
    "nha ve sinh": "nhà vệ sinh",
    "ban cong": "ban công",
    "san thuong": "sân thượng",
    "tang ham": "tầng hầm",
    "san vuon": "sân vườn",
    "gara": "ga-ra",
    "cua": "cửa",
    "cua so": "cửa sổ",
    "tuong": "tường",
    "san nha": "sàn nhà",
    "tran nha": "trần nhà",
    "mai nha": "mái nhà",
    "cau thang": "cầu thang",
    "thang may": "thang máy",
    "giuong": "giường",
    "tu": "tủ",
    "tu quan ao": "tủ quần áo",
    "ban": "bàn",
    "ghe": "ghế",
    "sofa": "ghế sô-pha",
    "ke sach": "kệ sách",
    "guong": "gương",
    "den": "đèn",
    "quat": "quạt",
    "dieu hoa": "điều hòa",
    "may giat": "máy giặt",
    "tu lanh": "tủ lạnh",
    "bep": "bếp",
    "lo vi song": "lò vi sóng",
    "noi": "nồi",
    "chao": "chảo",
    "bat": "bát",
    "dia": "đĩa",
    "dua": "đũa",
    "thia": "thìa",
    "nia": "nĩa",
    "dao": "dao",
    "coc": "cốc",
    "ly": "ly",
    "chai": "chai",
    "rem": "rèm",
    "tham": "thảm",
    "goi": "gối",
    "chan": "chăn",
    "khan": "khăn",
    "noi that": "nội thất",
    "do dung": "đồ dùng",
    "nha cua": "nhà cửa",
    
    # Transport
    "xe dap": "xe đạp",
    "xe may": "xe máy",
    "o to": "ô tô",
    "xe buyt": "xe buýt",
    "tau hoa": "tàu hỏa",
    "tau dien ngam": "tàu điện ngầm",
    "may bay": "máy bay",
    "tau thuy": "tàu thủy",
    "xe tai": "xe tải",
    "xe cuu thuong": "xe cứu thương",
    "xe cuu hoa": "xe cứu hỏa",
    "xe canh sat": "xe cảnh sát",
    "taxi": "taxi",
    "xe om": "xe ôm",
    "duong": "đường",
    "duong cao toc": "đường cao tốc",
    "cau": "cầu",
    "ham": "hầm",
    "nga tu": "ngã tư",
    "vong xoay": "vòng xoay",
    "den giao thong": "đèn giao thông",
    "bien bao": "biển báo",
    "via he": "vỉa hè",
    "lan duong": "làn đường",
    "bai do xe": "bãi đỗ xe",
    "tram xe buyt": "trạm xe buýt",
    "ga tau": "ga tàu",
    "san bay": "sân bay",
    "ben cang": "bến cảng",
    "lai xe": "lái xe",
    "di bo": "đi bộ",
    "chay": "chạy",
    "bay": "bay",
    "xuong xe": "xuống xe",
    "len xe": "lên xe",
    "do xe": "đỗ xe",
    "re trai": "rẽ trái",
    "re phai": "rẽ phải",
    "di thang": "đi thẳng",
    "quay lai": "quay lại",
    "ve xe": "vé xe",
    "bang lai": "bằng lái",
    "xang": "xăng",
    "dau": "dầu",
    "tram xang": "trạm xăng",
    "giao thong": "giao thông",
    "ket xe": "kẹt xe",
    "tai nan": "tai nạn",
    "phuong tien": "phương tiện",
    
    # Clothes
    "ao": "áo",
    "ao so mi": "áo sơ mi",
    "ao thun": "áo thun",
    "ao khoac": "áo khoác",
    "ao len": "áo len",
    "ao vest": "áo vest",
    "quan": "quần",
    "quan dai": "quần dài",
    "quan short": "quần short",
    "quan jean": "quần jean",
    "vay": "váy",
    "dam": "đầm",
    "ao dai": "áo dài",
    "do ngu": "đồ ngủ",
    "do lot": "đồ lót",
    "giay": "giày",
    "dep": "dép",
    "giay the thao": "giày thể thao",
    "giay cao got": "giày cao gót",
    "ung": "ủng",
    "tat": "tất",
    "vo": "vớ",
    "mu": "mũ",
    "non": "nón",
    "khan quang": "khăn quàng",
    "gang tay": "găng tay",
    "that lung": "thắt lưng",
    "ca vat": "cà vạt",
    "kinh": "kính",
    "dong ho": "đồng hồ",
    "nhan": "nhẫn",
    "vong co": "vòng cổ",
    "hoa tai": "hoa tai",
    "tui xach": "túi xách",
    "vi": "ví",
    "ba lo": "ba lô",
    "vali": "va-li",
    "o": "ô",
    "ao mua": "áo mưa",
    "mac": "mặc",
    "coi": "cởi",
    "di": "đi",
    "deo": "đeo",
    "thay do": "thay đồ",
    "mac dep": "mặc đẹp",
    "quan ao": "quần áo",
    "thoi trang": "thời trang",
    "co": "cỡ",
    "kich thuoc": "kích thước",
    "chat lieu": "chất liệu",
    "vai": "vải",
    "cotton": "cotton",
    "len": "len",
    "lua": "lụa",
    "da": "da",
    "nylon": "nylon",
    
    # Colors
    "mau": "màu",
    "do": "đỏ",
    "xanh la": "xanh lá",
    "xanh duong": "xanh dương",
    "vang": "vàng",
    "cam": "cam",
    "tim": "tím",
    "hong": "hồng",
    "trang": "trắng",
    "den": "đen",
    "xam": "xám",
    "nau": "nâu",
    "be": "be",
    "bac": "bạc",
    "vang dong": "vàng đồng",
    "mau sac": "màu sắc",
    "sang": "sáng",
    "toi": "tối",
    "nhat": "nhạt",
    "dam": "đậm",
    
    # Numbers
    "khong": "không",
    "mot": "một",
    "hai": "hai",
    "ba": "ba",
    "bon": "bốn",
    "nam": "năm",
    "sau": "sáu",
    "bay": "bảy",
    "tam": "tám",
    "chin": "chín",
    "muoi": "mười",
    "tram": "trăm",
    "nghin": "nghìn",
    "trieu": "triệu",
    "ty": "tỷ",
    "thu nhat": "thứ nhất",
    "thu hai": "thứ hai",
    "thu ba": "thứ ba",
    "so": "số",
    "so luong": "số lượng",
    "nhieu": "nhiều",
    "it": "ít",
    "tat ca": "tất cả",
    "khong co gi": "không có gì",
    "mot so": "một số",
    "phan tram": "phần trăm",
    "nua": "nửa",
    "mot phan tu": "một phần tư",
    "gap doi": "gấp đôi",
    "gap ba": "gấp ba",
    "so dem": "số đếm",
    
    # Health
    "suc khoe": "sức khỏe",
    "benh": "bệnh",
    "dau": "đau",
    "dau dau": "đau đầu",
    "dau bung": "đau bụng",
    "dau hong": "đau họng",
    "sot": "sốt",
    "ho": "ho",
    "so mui": "sổ mũi",
    "dau mat": "đau mắt",
    "dau rang": "đau răng",
    "chong mat": "chóng mặt",
    "buon non": "buồn nôn",
    "non": "nôn",
    "tieu chay": "tiêu chảy",
    "tao bon": "táo bón",
    "di ung": "dị ứng",
    "viem": "viêm",
    "nhiem trung": "nhiễm trùng",
    "ung thu": "ung thư",
    "tieu duong": "tiểu đường",
    "huyet ap cao": "huyết áp cao",
    "benh tim": "bệnh tim",
    "cam cum": "cảm cúm",
    "viem phoi": "viêm phổi",
    "thuoc": "thuốc",
    "vien thuoc": "viên thuốc",
    "thuoc giam dau": "thuốc giảm đau",
    "khang sinh": "kháng sinh",
    "vitamin": "vitamin",
    "tiem": "tiêm",
    "bang": "băng",
    "thuoc sat trung": "thuốc sát trùng",
    "bac si": "bác sĩ",
    "y ta": "y tá",
    "benh vien": "bệnh viện",
    "phong kham": "phòng khám",
    "nha thuoc": "nhà thuốc",
    "kham benh": "khám bệnh",
    "chua benh": "chữa bệnh",
    "dieu tri": "điều trị",
    "phau thuat": "phẫu thuật",
    "xet nghiem": "xét nghiệm",
    "chup X-quang": "chụp X-quang",
    "sieu am": "siêu âm",
    "don thuoc": "đơn thuốc",
    "bao hiem y te": "bảo hiểm y tế",
    "cap cuu": "cấp cứu",
    "khoe manh": "khỏe mạnh",
    "om": "ốm",
    "yeu": "yếu",
    "manh": "mạnh",
    "binh phuc": "bình phục",
    
    # School
    "truong": "trường",
    "truong hoc": "trường học",
    "truong mam non": "trường mầm non",
    "truong tieu hoc": "trường tiểu học",
    "truong trung hoc": "trường trung học",
    "truong dai hoc": "trường đại học",
    "lop hoc": "lớp học",
    "hoc sinh": "học sinh",
    "sinh vien": "sinh viên",
    "giao vien": "giáo viên",
    "giang vien": "giảng viên",
    "hieu truong": "hiệu trưởng",
    "mon hoc": "môn học",
    "toan": "toán",
    "van": "văn",
    "ly": "lý",
    "hoa": "hóa",
    "sinh": "sinh",
    "su": "sử",
    "dia": "địa",
    "tieng anh": "tiếng Anh",
    "tieng duc": "tiếng Đức",
    "the duc": "thể dục",
    "am nhac": "âm nhạc",
    "my thuat": "mỹ thuật",
    "tin hoc": "tin học",
    "bai hoc": "bài học",
    "bai tap": "bài tập",
    "bai kiem tra": "bài kiểm tra",
    "bai thi": "bài thi",
    "ky thi": "kỳ thi",
    "diem": "điểm",
    "diem so": "điểm số",
    "bang diem": "bảng điểm",
    "bang cap": "bằng cấp",
    "tot nghiep": "tốt nghiệp",
    "vao hoc": "vào học",
    "nghi hoc": "nghỉ học",
    "hoc bai": "học bài",
    "lam bai tap": "làm bài tập",
    "on tap": "ôn tập",
    "thi": "thi",
    "do": "đỗ",
    "truot": "trượt",
    "sach": "sách",
    "vo": "vở",
    "but": "bút",
    "thuc ke": "thước kẻ",
    "cap sach": "cặp sách",
    "bang den": "bảng đen",
    "phan": "phấn",
    "ban hoc": "bàn học",
    "thu vien": "thư viện",
    "phong thi nghiem": "phòng thí nghiệm",
    "san truong": "sân trường",
    "hoc tap": "học tập",
    "giao duc": "giáo dục",
    
    # Weather
    "thoi tiet": "thời tiết",
    "troi": "trời",
    "nang": "nắng",
    "mua": "mưa",
    "tuyet": "tuyết",
    "gio": "gió",
    "bao": "bão",
    "sam": "sấm",
    "chop": "chớp",
    "set": "sét",
    "suong mu": "sương mù",
    "may": "mây",
    "nhieu may": "nhiều mây",
    "it may": "ít mây",
    "quang dang": "quang đãng",
    "u am": "u ám",
    "nong": "nóng",
    "lanh": "lạnh",
    "am ap": "ấm áp",
    "mat me": "mát mẻ",
    "am uot": "ẩm ướt",
    "kho rao": "khô ráo",
    "nhiet do": "nhiệt độ",
    "do am": "độ ẩm",
    "do C": "độ C",
    "do F": "độ F",
    "mua xuan": "mùa xuân",
    "mua he": "mùa hè",
    "mua thu": "mùa thu",
    "mua dong": "mùa đông",
    "du bao": "dự báo",
    "du bao thoi tiet": "dự báo thời tiết",
    "o": "ô",
    "ao mua": "áo mưa",
    "ung": "ủng",
    "mua lon": "mưa lớn",
    "mua nho": "mưa nhỏ",
    "mua rao": "mưa rào",
    "mua dong": "mưa đông",
    "tuyet roi": "tuyết rơi",
    "dong bang": "đóng băng",
    "tan bang": "tan băng",
    "cau vong": "cầu vồng",
    
    # Daily routine
    "thuc day": "thức dậy",
    "danh rang": "đánh răng",
    "rua mat": "rửa mặt",
    "tam": "tắm",
    "mac quan ao": "mặc quần áo",
    "an sang": "ăn sáng",
    "an trua": "ăn trưa",
    "an toi": "ăn tối",
    "di lam": "đi làm",
    "di hoc": "đi học",
    "ve nha": "về nhà",
    "nau com": "nấu cơm",
    "don dep": "dọn dẹp",
    "lau nha": "lau nhà",
    "giat do": "giặt đồ",
    "la quan ao": "là quần áo",
    "di cho": "đi chợ",
    "mua sam": "mua sắm",
    "tap the duc": "tập thể dục",
    "doc sach": "đọc sách",
    "xem TV": "xem TV",
    "nghe nhac": "nghe nhạc",
    "choi game": "chơi game",
    "luot web": "lướt web",
    "gap ban": "gặp bạn",
    "di dao": "đi dạo",
    "nghi ngoi": "nghỉ ngơi",
    "di ngu": "đi ngủ",
    "thoi quen": "thói quen",
    "sinh hoat": "sinh hoạt",
    "hang ngay": "hàng ngày",
    "cuoc song": "cuộc sống",
    
    # Shopping
    "cua hang": "cửa hàng",
    "sieu thi": "siêu thị",
    "cho": "chợ",
    "trung tam thuong mai": "trung tâm thương mại",
    "mua": "mua",
    "ban": "bán",
    "gia": "giá",
    "re": "rẻ",
    "dat": "đắt",
    "giam gia": "giảm giá",
    "khuyen mai": "khuyến mãi",
    "mien phi": "miễn phí",
    "thanh toan": "thanh toán",
    "tien mat": "tiền mặt",
    "the": "thẻ",
    "hoa don": "hóa đơn",
    "bien lai": "biên lai",
    "doi tra": "đổi trả",
    "hoan tien": "hoàn tiền",
    "gio hang": "giỏ hàng",
    "hang hoa": "hàng hóa",
    "san pham": "sản phẩm",
    "chat luong": "chất lượng",
    "kich co": "kích cỡ",
    "mau sac": "màu sắc",
    "nhan hieu": "nhãn hiệu",
    "moi": "mới",
    "cu": "cũ",
    "that": "thật",
    "gia": "giả",
    "nguoi ban": "người bán",
    "nguoi mua": "người mua",
    "khach hang": "khách hàng",
    "nhan vien": "nhân viên",
    "thu": "thử",
    "chon": "chọn",
    "dat hang": "đặt hàng",
    "giao hang": "giao hàng",
    "mua sam": "mua sắm",
    "di mua sam": "đi mua sắm",
    
    # Sports
    "the thao": "thể thao",
    "bong da": "bóng đá",
    "bong ro": "bóng rổ",
    "bong chuyen": "bóng chuyền",
    "bong ban": "bóng bàn",
    "cau long": "cầu lông",
    "tennis": "quần vợt",
    "golf": "gôn",
    "boi loi": "bơi lội",
    "chay bo": "chạy bộ",
    "dap xe": "đạp xe",
    "leo nui": "leo núi",
    "truot tuyet": "trượt tuyết",
    "truot bang": "trượt băng",
    "yoga": "yoga",
    "gym": "phòng tập",
    "tap the duc": "tập thể dục",
    "van dong": "vận động",
    "thi dau": "thi đấu",
    "doi": "đội",
    "cau thu": "cầu thủ",
    "trong tai": "trọng tài",
    "huan luyen vien": "huấn luyện viên",
    "vo dich": "vô địch",
    "huy chuong": "huy chương",
    "cup": "cúp",
    "giai dau": "giải đấu",
    "olympic": "Olympic",
    "world cup": "World Cup",
    "thang": "thắng",
    "thua": "thua",
    "hoa": "hòa",
    "ban thang": "bàn thắng",
    "diem": "điểm",
    "san bong": "sân bóng",
    "ho boi": "hồ bơi",
    "phong tap": "phòng tập",
    "suc khoe": "sức khỏe",
    "tap luyen": "tập luyện",
    
    # Technology
    "cong nghe": "công nghệ",
    "may tinh": "máy tính",
    "laptop": "laptop",
    "dien thoai": "điện thoại",
    "smartphone": "điện thoại thông minh",
    "may tinh bang": "máy tính bảng",
    "man hinh": "màn hình",
    "ban phim": "bàn phím",
    "chuot": "chuột",
    "o cung": "ổ cứng",
    "USB": "USB",
    "tai nghe": "tai nghe",
    "loa": "loa",
    "may in": "máy in",
    "may scan": "máy scan",
    "may anh": "máy ảnh",
    "may quay": "máy quay",
    "internet": "internet",
    "wifi": "wifi",
    "mang": "mạng",
    "website": "trang web",
    "ung dung": "ứng dụng",
    "phan mem": "phần mềm",
    "he dieu hanh": "hệ điều hành",
    "trinh duyet": "trình duyệt",
    "email": "email",
    "mang xa hoi": "mạng xã hội",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "YouTube": "YouTube",
    "TikTok": "TikTok",
    "tin nhan": "tin nhắn",
    "cuoc goi": "cuộc gọi",
    "video call": "gọi video",
    "tai xuong": "tải xuống",
    "tai len": "tải lên",
    "luu tru": "lưu trữ",
    "dam may": "đám mây",
    "mat khau": "mật khẩu",
    "tai khoan": "tài khoản",
    "dang nhap": "đăng nhập",
    "dang xuat": "đăng xuất",
    "virus": "virus",
    "bao mat": "bảo mật",
    "cap nhat": "cập nhật",
    "sac pin": "sạc pin",
    "ket noi": "kết nối",
    "khong day": "không dây",
    
    # Nature
    "thien nhien": "thiên nhiên",
    "troi": "trời",
    "dat": "đất",
    "nuoc": "nước",
    "lua": "lửa",
    "khong khi": "không khí",
    "mat troi": "mặt trời",
    "mat trang": "mặt trăng",
    "sao": "sao",
    "nui": "núi",
    "doi": "đồi",
    "thung lung": "thung lũng",
    "song": "sông",
    "ho": "hồ",
    "bien": "biển",
    "dai duong": "đại dương",
    "bai bien": "bãi biển",
    "dao": "đảo",
    "rung": "rừng",
    "cay": "cây",
    "hoa": "hoa",
    "co": "cỏ",
    "la": "lá",
    "qua": "quả",
    "hat": "hạt",
    "re": "rễ",
    "canh": "cành",
    "than cay": "thân cây",
    "da": "đá",
    "cat": "cát",
    "bun": "bùn",
    "suoi": "suối",
    "thac nuoc": "thác nước",
    "dong co": "đồng cỏ",
    "canh dong": "cánh đồng",
    "sa mac": "sa mạc",
    "bac cuc": "bắc cực",
    "nam cuc": "nam cực",
    "khi hau": "khí hậu",
    "moi truong": "môi trường",
    "o nhiem": "ô nhiễm",
    "bao ve": "bảo vệ",
    "tai nguyen": "tài nguyên",
    "dong vat hoang da": "động vật hoang dã",
    "thuc vat": "thực vật",
    
    # Professions
    "nghe nghiep": "nghề nghiệp",
    "cong viec": "công việc",
    "bac si": "bác sĩ",
    "y ta": "y tá",
    "duoc si": "dược sĩ",
    "giao vien": "giáo viên",
    "ky su": "kỹ sư",
    "kien truc su": "kiến trúc sư",
    "luat su": "luật sư",
    "ke toan": "kế toán",
    "nhan vien van phong": "nhân viên văn phòng",
    "nhan vien ban hang": "nhân viên bán hàng",
    "thu ky": "thư ký",
    "giam doc": "giám đốc",
    "doanh nhan": "doanh nhân",
    "canh sat": "cảnh sát",
    "linh cuu hoa": "lính cứu hỏa",
    "bo doi": "bộ đội",
    "phi cong": "phi công",
    "tiep vien hang khong": "tiếp viên hàng không",
    "tai xe": "tài xế",
    "dau bep": "đầu bếp",
    "phuc vu": "phục vụ",
    "tho may": "thợ may",
    "tho dien": "thợ điện",
    "tho sua ong nuoc": "thợ sửa ống nước",
    "tho moc": "thợ mộc",
    "tho xay": "thợ xây",
    "nong dan": "nông dân",
    "ngu dan": "ngư dân",
    "nha bao": "nhà báo",
    "nhac si": "nhạc sĩ",
    "ca si": "ca sĩ",
    "dien vien": "diễn viên",
    "dao dien": "đạo diễn",
    "hoa si": "họa sĩ",
    "nhiep anh gia": "nhiếp ảnh gia",
    "lap trinh vien": "lập trình viên",
    "nha khoa hoc": "nhà khoa học",
    "bau troi": "bầu trời",
    
    # Hobbies
    "so thich": "sở thích",
    "doc sach": "đọc sách",
    "viet lach": "viết lách",
    "ve": "vẽ",
    "chup anh": "chụp ảnh",
    "quay phim": "quay phim",
    "nghe nhac": "nghe nhạc",
    "choi nhac": "chơi nhạc",
    "hat": "hát",
    "nhay": "nhảy",
    "xem phim": "xem phim",
    "xem TV": "xem TV",
    "choi game": "chơi game",
    "choi co": "chơi cờ",
    "nau an": "nấu ăn",
    "lam banh": "làm bánh",
    "lam vuon": "làm vườn",
    "trong cay": "trồng cây",
    "nuoi thu cung": "nuôi thú cưng",
    "cau ca": "câu cá",
    "di cam trai": "đi cắm trại",
    "di phuot": "đi phượt",
    "du lich": "du lịch",
    "tham quan": "tham quan",
    "di dao": "đi dạo",
    "di mua sam": "đi mua sắm",
    "tap the duc": "tập thể dục",
    "choi the thao": "chơi thể thao",
    "yoga": "yoga",
    "thien": "thiền",
    "hoc ngoai ngu": "học ngoại ngữ",
    "suu tam": "sưu tầm",
    "theu": "thêu",
    "dan len": "đan len",
    "gap giay": "gấp giấy",
    "xep hinh": "xếp hình",
    "giai o": "giải ô",
    "giai tri": "giải trí",
    "thu gian": "thư giãn",
    
    # Travel
    "du lich": "du lịch",
    "di du lich": "đi du lịch",
    "chuyen di": "chuyến đi",
    "hanh trinh": "hành trình",
    "diem den": "điểm đến",
    "khach san": "khách sạn",
    "nha nghi": "nhà nghỉ",
    "phong": "phòng",
    "dat phong": "đặt phòng",
    "nhan phong": "nhận phòng",
    "tra phong": "trả phòng",
    "ve may bay": "vé máy bay",
    "ve tau": "vé tàu",
    "ve xe": "vé xe",
    "ho chieu": "hộ chiếu",
    "visa": "visa",
    "hanh ly": "hành lý",
    "vali": "va-li",
    "balo": "ba lô",
    "ban do": "bản đồ",
    "huong dan vien": "hướng dẫn viên",
    "tour": "tour",
    "dich vu": "dịch vụ",
    "nha hang": "nhà hàng",
    "quan ca phe": "quán cà phê",
    "dia diem tham quan": "địa điểm tham quan",
    "bai bien": "bãi biển",
    "nui": "núi",
    "ho": "hồ",
    "thac nuoc": "thác nước",
    "rung": "rừng",
    "di tich": "di tích",
    "bao tang": "bảo tàng",
    "den": "đền",
    "chua": "chùa",
    "nha tho": "nhà thờ",
    "lau dai": "lâu đài",
    "cung dien": "cung điện",
    "cong vien": "công viên",
    "vuon bach thu": "vườn bách thú",
    "bien bao": "biển báo",
    "thong tin": "thông tin",
    "loi vao": "lối vào",
    "loi ra": "lối ra",
    "tham quan": "tham quan",
    "nghi duong": "nghỉ dưỡng",
    "kham pha": "khám phá",
    
    # Restaurant
    "nha hang": "nhà hàng",
    "quan an": "quán ăn",
    "quan ca phe": "quán cà phê",
    "thuc don": "thực đơn",
    "mon an": "món ăn",
    "mon chinh": "món chính",
    "mon khai vi": "món khai vị",
    "mon trang mieng": "món tráng miệng",
    "do uong": "đồ uống",
    "goi mon": "gọi món",
    "phuc vu": "phục vụ",
    "ban": "bàn",
    "dat ban": "đặt bàn",
    "thanh toan": "thanh toán",
    "hoa don": "hóa đơn",
    "tien tip": "tiền tip",
    "ngon": "ngon",
    "do": "dở",
    "cay": "cay",
    "ngot": "ngọt",
    "man": "mặn",
    "chua": "chua",
    "dang": "đắng",
    "beo": "béo",
    "nhat": "nhạt",
    "nong": "nóng",
    "nguoi": "nguội",
    "lanh": "lạnh",
    "an": "ăn",
    "uong": "uống",
    "an trua": "ăn trưa",
    "an toi": "ăn tối",
    "an sang": "ăn sáng",
    "dau bep": "đầu bếp",
    "nhan vien": "nhân viên",
    "bep": "bếp",
    "nau": "nấu",
    "chien": "chiên",
    "xao": "xào",
    "nuong": "nướng",
    "luoc": "luộc",
    "hap": "hấp",
    "tron": "trộn",
    "cat": "cắt",
    "thai": "thái",
    "bang": "băm",
    
    # Verbs with prepositions
    "phu thuoc vao": "phụ thuộc vào",
    "tin tuong vao": "tin tưởng vào",
    "tham gia vao": "tham gia vào",
    "dau tu vao": "đầu tư vào",
    "nghien cuu ve": "nghiên cứu về",
    "bao cao ve": "báo cáo về",
    "thac mac ve": "thắc mắc về",
    "lo lang ve": "lo lắng về",
    "hat ve": "hát về",
    "viet ve": "viết về",
    "noi ve": "nói về",
    "nghi ve": "nghĩ về",
    "hoi ve": "hỏi về",
    "quan tam den": "quan tâm đến",
    "tham gia": "tham gia",
    "thuoc ve": "thuộc về",
    "lien quan den": "liên quan đến",
    "phan doi": "phản đối",
    "dong y voi": "đồng ý với",
    "lien lac voi": "liên lạc với",
    "gap go voi": "gặp gỡ với",
    "ket hon voi": "kết hôn với",
    "ly hon voi": "ly hôn với",
    "lam viec voi": "làm việc với",
    "hop tac voi": "hợp tác với",
    "canh tranh voi": "cạnh tranh với",
    "so sanh voi": "so sánh với",
    "ket noi voi": "kết nối với",
    "phan biet voi": "phân biệt với",
    "giong voi": "giống với",
    "khac voi": "khác với",
    "hai long voi": "hài lòng với",
    "bat man voi": "bất mãn với",
    "kinh nghiem voi": "kinh nghiệm với",
    "doi mat voi": "đối mặt với",
    "chiu dung voi": "chịu đựng với",
    "cho doi": "chờ đợi",
    "mong cho": "mong chờ",
    "tim kiem": "tìm kiếm",
    "nhin vao": "nhìn vào",
    "nghe theo": "nghe theo",
    "chay khoi": "chạy khỏi",
    "thoat khoi": "thoát khỏi",
    "phu thuoc": "phụ thuộc",
    "tin tuong": "tin tưởng",
    "hy vong": "hy vọng",
    "mong uoc": "mong ước",
    "so hai": "sợ hãi",
    "lo au": "lo âu",
    "dam me": "đam mê",
    "yeu thich": "yêu thích",
    "ghet bo": "ghét bỏ",
    "chan nan": "chán nản",
    "vui mung": "vui mừng",
    "buon phien": "buồn phiền",
    "tuc gian": "tức giận",
    "ngac nhien": "ngạc nhiên",
    "that vong": "thất vọng",
    "tu hao": "tự hào",
    "xau ho": "xấu hổ",
    
    # Noun-verb combinations
    "tham du hoi nghi": "tham dự hội nghị",
    "to chuc su kien": "tổ chức sự kiện",
    "dua ra quyet dinh": "đưa ra quyết định",
    "dat muc tieu": "đặt mục tiêu",
    "thuc hien ke hoach": "thực hiện kế hoạch",
    "giai quyet van de": "giải quyết vấn đề",
    "dap ung yeu cau": "đáp ứng yêu cầu",
    "hoan thanh nhiem vu": "hoàn thành nhiệm vụ",
    "cung cap dich vu": "cung cấp dịch vụ",
    "tao an tuong": "tạo ấn tượng",
    "gay chu y": "gây chú ý",
    "dat ket qua": "đạt kết quả",
    "mang lai loi ich": "mang lại lợi ích",
    "chap nhan thach thuc": "chấp nhận thách thức",
    "doi pho voi kho khan": "đối phó với khó khăn",
    "tien hanh nghien cuu": "tiến hành nghiên cứu",
    "ap dung phuong phap": "áp dụng phương pháp",
    "phan tich du lieu": "phân tích dữ liệu",
    "xay dung he thong": "xây dựng hệ thống",
    "phat trien ung dung": "phát triển ứng dụng",
    "thiet ke giao dien": "thiết kế giao diện",
    "kiem tra chat luong": "kiểm tra chất lượng",
    "sua chua loi": "sửa chữa lỗi",
    "cap nhat phan mem": "cập nhật phần mềm",
    "bao tri he thong": "bảo trì hệ thống",
    "dao tao nhan vien": "đào tạo nhân viên",
    "tuyen dung nhan su": "tuyển dụng nhân sự",
    "danh gia hieu qua": "đánh giá hiệu quả",
    "de xuat y tuong": "đề xuất ý tưởng",
    "trinh bay bao cao": "trình bày báo cáo",
    "hoan thanh cong viec": "hoàn thành công việc",
    
    # Additional missing words
    "Chuc ngon mieng!": "Chúc ngon miệng!",
    "Dem Giao thua": "Đêm Giao thừa",
    "Giang sinh": "Giáng sinh",
    "Le Phuc Sinh": "Lễ Phục Sinh",
    "Nam moi": "Năm mới",
    "Tinh tien!": "Tính tiền!",
    "an mung": "ăn mừng",
    "anh nang": "ánh nắng",
    "ao blouse": "áo blouse",
    "ao choang": "áo choàng",
    "ba muoi": "ba mươi",
    "bac si (nam)": "bác sĩ (nam)",
    "bac si (nu)": "bác sĩ (nữ)",
    "bac si nu": "bác sĩ nữ",
    "bai danh gia": "bài đánh giá",
    "bai hat": "bài hát",
    "bai tap ve nha": "bài tập về nhà",
    "bai thuyet trinh": "bài thuyết trình",
    "ban an": "bàn ăn",
    "ban nhac": "ban nhạc",
    "ban tra": "bàn trà",
    "bang lai xe": "bằng lái xe",
    "banh mi nho": "bánh mì nhỏ",
    "banh sinh nhat": "bánh sinh nhật",
    "bao co sam set": "bão có sấm sét",
    "bap rang": "bắp rang",
    "bat luc": "bất lực",
    "bay muoi": "bảy mươi",
    "ben canh": "bên cạnh",
    "ben phai": "bên phải",
    "ben trai": "bên trái",
    "bi quan": "bi quan",
    "bi thuong": "bị thương",
    "bi ton thuong": "bị tổn thương",
    "bi xuc pham": "bị xúc phạm",
    "biet on": "biết ơn",
    "bo bien": "bờ biển",
    "bo dinh tuyen": "bộ định tuyến",
    "bo nho": "bộ nhớ",
    "boi roi": "bối rối",
    "boi": "bơi",
    "bon muoi": "bốn mươi",
    "bot mi": "bột mì",
    "bot nhan": "bột nhân",
    "buoi chieu": "buổi chiều",
    "buoi cong chieu": "buổi công chiếu",
    "buoi hop": "buổi họp",
    "buoi sang": "buổi sáng",
    "buoi toi": "buổi tối",
    "buon ba": "buồn bã",
    "buon cuoi": "buồn cười",
    "buon ngu": "buồn ngủ",
    "buon rau": "buồn rầu",
    "cai ao": "cái áo",
    "cai ban chai": "cái bàn chải",
    "cai chen": "cái chén",
    "cai tui": "cái túi",
    "canh bao": "cảnh báo",
    "canh sat giao thong": "cảnh sát giao thông",
    "cap nhat": "cập nhật",
    "cau be": "cậu bé",
    "cau chuyen": "câu chuyện",
    "cay co bong mat": "cây có bóng mát",
    "cay trong": "cây trồng",
    "cha me": "cha mẹ",
    "chan khong": "chân không",
    "chan noi": "chán nói",
    "chat beo": "chất béo",
    "chat xo": "chất xơ",
    "chay dua": "chạy đua",
    "chen an": "chén ăn",
    "chi phi sinh hoat": "chi phí sinh hoạt",
    "chi so": "chỉ số",
    "chi tiet": "chi tiết",
    "chiec may": "chiếc máy",
    "chiec xe": "chiếc xe",
    "chin muoi": "chín mươi",
    "cho doi": "chờ đợi",
    "cho hang": "chợ hàng",
    "cho ngoi": "chỗ ngồi",
    "chon vui": "chôn vùi",
    "chu de": "chủ đề",
    "chu nhan": "chủ nhân",
    "chu so huu": "chủ sở hữu",
    "chuan bi": "chuẩn bị",
    "chuc mung": "chúc mừng",
    "chuyen bay": "chuyến bay",
    "chuyen di": "chuyến đi",
    "chuyen gia": "chuyên gia",
    "co be": "cô bé",
    "co gai": "cô gái",
    "co gang": "cố gắng",
    "co hoi": "cơ hội",
    "coc nuoc": "cốc nước",
    "con bo": "con bò",
    "con duong": "con đường",
    "con gai": "con gái",
    "con nguoi": "con người",
    "cong viec nha": "công việc nhà",
    "cu cai": "củ cải",
    "cua khau": "cửa khẩu",
    "cua so": "cửa sổ",
    "cuoi cung": "cuối cùng",
    "cuoi tuan": "cuối tuần",
    "cuon sach": "cuốn sách",
    "cuu ho": "cứu hộ",
    "dam cuoi": "đám cưới",
    "dan ong": "đàn ông",
    "dat nuoc": "đất nước",
    "dau an": "dấu ấn",
    "dau bep": "đầu bếp",
    "dau cham": "dấu chấm",
    "dau hoi": "dấu hỏi",
    "dau mua": "đầu mùa",
    "dau tien": "đầu tiên",
    "de thuong": "dễ thương",
    "dem dem": "đêm đêm",
    "dem nay": "đêm nay",
    "di chuyen": "di chuyển",
    "di dong": "di động",
    "di san": "di sản",
    "dia chi": "địa chỉ",
    "dia diem": "địa điểm",
    "dia phuong": "địa phương",
    "dich benh": "dịch bệnh",
    "dien thoai di dong": "điện thoại di động",
    "dien tu": "điện tử",
    "dieu can": "điều cần",
    "dieu hanh": "điều hành",
    "dieu khien": "điều khiển",
    "dinh cu": "định cư",
    "dinh duong": "dinh dưỡng",
    "doi ngu": "đội ngũ",
    "doi song": "đời sống",
    "don dat hang": "đơn đặt hàng",
    "don gian": "đơn giản",
    "dong bang": "đồng bằng",
    "dong ho deo tay": "đồng hồ đeo tay",
    "dong phuc": "đồng phục",
    "dong xu": "đồng xu",
    "du kien": "dự kiến",
    "du thao": "dự thảo",
    "dua hau": "dưa hấu",
    "dua leo": "dưa leo",
    "duong di": "đường đi",
    "duong pho": "đường phố",
    "duong ray": "đường ray",
    "duong sat": "đường sắt",
    "em be": "em bé",
    "em gai": "em gái",
    "em trai": "em trai",
    "gia ca phe": "giá cà phê",
    "gia cam": "gia cầm",
    "gia dinh nho": "gia đình nhỏ",
    "gia vi": "gia vị",
    "giac ngu": "giấc ngủ",
    "giai doan": "giai đoạn",
    "giai phap": "giải pháp",
    "giam doc": "giám đốc",
    "gian nan": "gian nan",
    "giao duc": "giáo dục",
    "giao su": "giáo sư",
    "giay chung nhan": "giấy chứng nhận",
    "giay dep": "giày dép",
    "giay phep": "giấy phép",
    "giay to": "giấy tờ",
    "gio lam viec": "giờ làm việc",
    "gio mo cua": "giờ mở cửa",
    "gioi han": "giới hạn",
    "giong noi": "giọng nói",
    "giu gin": "giữ gìn",
    "go cua": "gõ cửa",
    "goi y": "gợi ý",
    "gui thu": "gửi thư",
    "ha muoi": "hạ mươi",
    "hai long": "hài lòng",
    "hai muoi": "hai mươi",
    "hang hoa": "hàng hóa",
    "hang ngay": "hàng ngày",
    "hang xom": "hàng xóm",
    "hanh dong": "hành động",
    "hanh khach": "hành khách",
    "hanh lang": "hành lang",
    "hanh ly": "hành lý",
    "hanh trinh": "hành trình",
    "hao huc": "háo hức",
    "hau boi": "hậu bồi",
    "hau qua": "hậu quả",
    "he dieu hanh": "hệ điều hành",
    "he mat troi": "hệ mặt trời",
    "he thong": "hệ thống",
    "hen gap lai": "hẹn gặp lại",
    "hien dai": "hiện đại",
    "hien tai": "hiện tại",
    "hien tuong": "hiện tượng",
    "hieu biet": "hiểu biết",
    "hieu qua": "hiệu quả",
    "hinh anh": "hình ảnh",
    "hinh thuc": "hình thức",
    "ho boi": "hồ bơi",
    "ho nuoc": "hồ nước",
    "ho so": "hồ sơ",
    "hoa don": "hóa đơn",
    "hoa hong": "hoa hồng",
    "hoa qua": "hoa quả",
    "hoac": "hoặc",
    "hoang hon": "hoàng hôn",
    "hoat dong": "hoạt động",
    "hoi dap": "hỏi đáp",
    "hoi nghi": "hội nghị",
    "hom qua": "hôm qua",
    "hon nhan": "hôn nhân",
    "hong": "hồng",
    "hop tac": "hợp tác",
    "hu hong": "hư hỏng",
    "huong dan": "hướng dẫn",
    "huong vi": "hương vị",
    "ke ca": "kể cả",
    "ke hoach": "kế hoạch",
    "ket qua": "kết quả",
    "keu goi": "kêu gọi",
    "khac biet": "khác biệt",
    "khai thac": "khai thác",
    "kham pha": "khám phá",
    "khan cap": "khẩn cấp",
    "khao sat": "khảo sát",
    "khi hau": "khí hậu",
    "khi quyen": "khí quyển",
    "khieu nai": "khiếu nại",
    "kho chiu": "khó chịu",
    "kho khan": "khó khăn",
    "khoa hoc": "khoa học",
    "khoan": "khoản",
    "khong gian": "không gian",
    "khu vuc": "khu vực",
    "khung hoang": "khủng hoảng",
    "kien thuc": "kiến thức",
    "kien truc": "kiến trúc",
    "kiem soat": "kiểm soát",
    "kinh te": "kinh tế",
    "ky nang": "kỹ năng",
    "ky thuat": "kỹ thuật",
    "la thu": "lá thư",
    "lac quan": "lạc quan",
    "lai suat": "lãi suất",
    "lam ban": "làm bạn",
    "lam bep": "làm bếp",
    "lam cha me": "làm cha mẹ",
    "lam quen": "làm quen",
    "lan dau": "lần đầu",
    "lang nghe": "lắng nghe",
    "lanh dao": "lãnh đạo",
    "lap trinh vien": "lập trình viên",
    "lau dai": "lâu dài",
    "le hoi": "lễ hội",
    "len men": "lên men",
    "lich su": "lịch sử",
    "linh hoat": "linh hoạt",
    "linh vuc": "lĩnh vực",
    "lo au": "lo âu",
    "lo ngai": "lo ngại",
    "lo trinh": "lộ trình",
    "loi cam on": "lời cảm ơn",
    "loi chao": "lời chào",
    "loi ich": "lợi ích",
    "loi khuyen": "lời khuyên",
    "loi noi": "lời nói",
    "lop hoc": "lớp học",
    "lop tre": "lớp trẻ",
    "luan van": "luận văn",
    "luat phap": "luật pháp",
    "luc luong": "lực lượng",
    "lua chon": "lựa chọn",
    "luu tru": "lưu trữ",
    "ly do": "lý do",
    "ly lich": "lý lịch",
    "ma pin": "mã pin",
    "ma so": "mã số",
    "mang luoi": "mạng lưới",
    "manh me": "mạnh mẽ",
    "mat bang": "mặt bằng",
    "mat hang": "mặt hàng",
    "mat na": "mặt nạ",
    "mat tien": "mặt tiền",
    "mat troi": "mặt trời",
    "mat trang": "mặt trăng",
    "mau ao": "mẫu áo",
    "may bay": "máy bay",
    "may chieu": "máy chiếu",
    "may dem": "máy đếm",
    "may dieu hoa": "máy điều hòa",
    "may giat": "máy giặt",
    "may hut bui": "máy hút bụi",
    "may in": "máy in",
    "may lanh": "máy lạnh",
    "may loc": "máy lọc",
    "may pha": "máy pha",
    "may rua bat": "máy rửa bát",
    "may say": "máy sấy",
    "may tinh": "máy tính",
    "may vi tinh": "máy vi tính",
    "me nuoi": "mẹ nuôi",
    "mo cua": "mở cửa",
    "mo hinh": "mô hình",
    "mo ta": "mô tả",
    "moi quan he": "mối quan hệ",
    "moi truong": "môi trường",
    "mon hoc": "môn học",
    "mong muon": "mong muốn",
    "mot chut": "một chút",
    "mot minh": "một mình",
    "mot ngay": "một ngày",
    "mot so": "một số",
    "mua dong": "mùa đông",
    "mua he": "mùa hè",
    "mua thu": "mùa thu",
    "mua xuan": "mùa xuân",
    "muc dich": "mục đích",
    "muc tieu": "mục tiêu",
    "muoi hai": "mười hai",
    "muoi mot": "mười một",
    "nam muoi": "năm mươi",
    "nang cao": "nâng cao",
    "nang luong": "năng lượng",
    "nang suat": "năng suất",
    "nau an": "nấu ăn",
    "ngam nhin": "ngắm nhìn",
    "ngan sach": "ngân sách",
    "ngay dau tien": "ngày đầu tiên",
    "ngay hom nay": "ngày hôm nay",
    "ngay le": "ngày lễ",
    "ngay nghi": "ngày nghỉ",
    "ngay sinh": "ngày sinh",
    "ngay thuong": "ngày thường",
    "nghe nghiep": "nghề nghiệp",
    "nghe si": "nghệ sĩ",
    "nghe thuat": "nghệ thuật",
    "nghi ngo": "nghi ngờ",
    "nghiem tuc": "nghiêm túc",
    "nghien cuu": "nghiên cứu",
    "ngo ngang": "ngỡ ngàng",
    "ngon ngu": "ngôn ngữ",
    "ngu phap": "ngữ pháp",
    "nguoi ban": "người bán",
    "nguoi cham soc": "người chăm sóc",
    "nguoi dep": "người đẹp",
    "nguoi dung": "người dùng",
    "nguoi gia": "người già",
    "nguoi lon": "người lớn",
    "nguoi mau": "người mẫu",
    "nguoi mua": "người mua",
    "nguoi nuoc ngoai": "người nước ngoài",
    "nguoi than": "người thân",
    "nguoi yeu": "người yêu",
    "nguon goc": "nguồn gốc",
    "nguon luc": "nguồn lực",
    "nguon von": "nguồn vốn",
    "nha bao": "nhà báo",
    "nha cung cap": "nhà cung cấp",
    "nha ga": "nhà ga",
    "nha khoa": "nhà khoa",
    "nha may": "nhà máy",
    "nha nuoc": "nhà nước",
    "nha rieng": "nhà riêng",
    "nha san xuat": "nhà sản xuất",
    "nha tho": "nhà thờ",
    "nhan hieu": "nhãn hiệu",
    "nhan sac": "nhan sắc",
    "nhan su": "nhân sự",
    "nhan to": "nhân tố",
    "nhan vat": "nhân vật",
    "nhan vien": "nhân viên",
    "nhiem vu": "nhiệm vụ",
    "nhiet do": "nhiệt độ",
    "nhin chung": "nhìn chung",
    "nho be": "nhỏ bé",
    "nho nhat": "nhỏ nhất",
    "nhom": "nhóm",
    "nhu cau": "nhu cầu",
    "nhung": "những",
    "nien do": "niên độ",
    "no luc": "nỗ lực",
    "noi dung": "nội dung",
    "noi lam viec": "nơi làm việc",
    "noi o": "nơi ở",
    "noi tieng": "nổi tiếng",
    "nong trai": "nông trại",
    "nuoc bia": "nước bia",
    "nuoc chanh": "nước chanh",
    "nuoc hoa": "nước hoa",
    "nuoc ngoai": "nước ngoài",
    "nuoc uong": "nước uống",
    "o to": "ô tô",
    "ong noi": "ông nội",
    "phai khong": "phải không",
    "phan anh": "phản ánh",
    "phan biet": "phân biệt",
    "phan hoi": "phản hồi",
    "phan mem": "phần mềm",
    "phan ung": "phản ứng",
    "phap luat": "pháp luật",
    "phat hien": "phát hiện",
    "phat minh": "phát minh",
    "phat trien": "phát triển",
    "phen nua": "phần nữa",
    "phi hanh doan": "phi hành đoàn",
    "phia sau": "phía sau",
    "phia truoc": "phía trước",
    "phim truyen": "phim truyện",
    "phong cach": "phong cách",
    "phong cam": "phong cảm",
    "pho bien": "phổ biến",
    "phu hop": "phù hợp",
    "phu nu": "phụ nữ",
    "phu trach": "phụ trách",
    "phuong an": "phương án",
    "phuong dien": "phương diện",
    "phuong phap": "phương pháp",
    "phuong thuc": "phương thức",
    "phuong tien": "phương tiện",
    "quan an": "quán ăn",
    "quan cao": "quảng cáo",
    "quan he": "quan hệ",
    "quan ly": "quản lý",
    "quan sat": "quan sát",
    "quan tam": "quan tâm",
    "quang truong": "quảng trường",
    "quat dien": "quạt điện",
    "que huong": "quê hương",
    "qui trinh": "quy trình",
    "quoc gia": "quốc gia",
    "quoc te": "quốc tế",
    "quyen loi": "quyền lợi",
    "quyen sach": "quyển sách",
    "ra mat": "ra mắt",
    "rang buoc": "ràng buộc",
    "rau cu": "rau củ",
    "rau xanh": "rau xanh",
    "rieng tu": "riêng tư",
    "ro rang": "rõ ràng",
    "rui ro": "rủi ro",
    "rung cay": "rừng cây",
    "ruou vang": "rượu vàng",
    "san bay": "sân bay",
    "san bong": "sân bóng",
    "san khau": "sân khấu",
    "san xuat": "sản xuất",
    "sang kien": "sáng kiến",
    "sang mai": "sáng mai",
    "sang nay": "sáng nay",
    "sang tao": "sáng tạo",
    "sau muoi": "sáu mươi",
    "sieu thi": "siêu thị",
    "sinh hoat": "sinh hoạt",
    "sinh vien": "sinh viên",
    "so do": "sơ đồ",
    "so luoc": "sơ lược",
    "so tay": "sổ tay",
    "son moi": "son môi",
    "su co": "sự cố",
    "su dung": "sử dụng",
    "su kien": "sự kiện",
    "su that": "sự thật",
    "sua chua": "sửa chữa",
    "suon": "sườn",
    "ta chuc": "tạ chức",
    "tai lieu": "tài liệu",
    "tai nan": "tai nạn",
    "tai san": "tài sản",
    "tam biet": "tạm biệt",
    "tam ly": "tâm lý",
    "tam su": "tâm sự",
    "tam thoi": "tạm thời",
    "tam trang": "tâm trạng",
    "tan dung": "tận dụng",
    "tan huong": "tận hưởng",
    "tap chi": "tạp chí",
    "tap huan": "tập huấn",
    "tap the": "tập thể",
    "tau dien": "tàu điện",
    "tau hoa": "tàu hỏa",
    "tau ngam": "tàu ngầm",
    "ten goi": "tên gọi",
    "the gioi": "thế giới",
    "the ky": "thế kỷ",
    "the nao": "thế nào",
    "the thao": "thể thao",
    "thi nghiem": "thí nghiệm",
    "thi truong": "thị trường",
    "thich hop": "thích hợp",
    "thien nhien": "thiên nhiên",
    "thiet bi": "thiết bị",
    "thiet ke": "thiết kế",
    "thinh hanh": "thịnh hành",
    "tho xay": "thợ xây",
    "thoi dai": "thời đại",
    "thoi diem": "thời điểm",
    "thoi gian": "thời gian",
    "thoi ky": "thời kỳ",
    "thong bao": "thông báo",
    "thong ke": "thống kê",
    "thong minh": "thông minh",
    "thong nhat": "thống nhất",
    "thong tin": "thông tin",
    "thu cong": "thủ công",
    "thu do": "thủ đô",
    "thu gian": "thư giãn",
    "thu hut": "thu hút",
    "thu nhap": "thu nhập",
    "thu tuc": "thủ tục",
    "thu vien": "thư viện",
    "thuc an": "thức ăn",
    "thuc hien": "thực hiện",
    "thuc pham": "thực phẩm",
    "thuc te": "thực tế",
    "thuong mai": "thương mại",
    "thuong xuyen": "thường xuyên",
    "ti le": "tỉ lệ",
    "tich cuc": "tích cực",
    "tien bo": "tiến bộ",
    "tien do": "tiến độ",
    "tien ich": "tiện ích",
    "tien nghi": "tiện nghi",
    "tiep can": "tiếp cận",
    "tiep nhan": "tiếp nhận",
    "tiep theo": "tiếp theo",
    "tiep tuc": "tiếp tục",
    "tiep xuc": "tiếp xúc",
    "tinh hinh": "tình hình",
    "tinh trang": "tình trạng",
    "tinh yeu": "tình yêu",
    "to chuc": "tổ chức",
    "to hop": "tổ hợp",
    "toan bo": "toàn bộ",
    "toan cau": "toàn cầu",
    "toc do": "tốc độ",
    "toi da": "tối đa",
    "toi thieu": "tối thiểu",
    "toi uu": "tối ưu",
    "tom tat": "tóm tắt",
    "tong hop": "tổng hợp",
    "tong quat": "tổng quát",
    "tong so": "tổng số",
    "tra gop": "trả góp",
    "tra loi": "trả lời",
    "trai dat": "trái đất",
    "trai nghiem": "trải nghiệm",
    "tram xe buyt": "trạm xe buýt",
    "trang bi": "trang bị",
    "trang phuc": "trang phục",
    "trang thai": "trạng thái",
    "trang web": "trang web",
    "tre em": "trẻ em",
    "tre tuoi": "trẻ tuổi",
    "trinh do": "trình độ",
    "tro chuyen": "trò chuyện",
    "tro giup": "trợ giúp",
    "trong tam": "trọng tâm",
    "truong hop": "trường hợp",
    "tu nhien": "tự nhiên",
    "tu truyen": "tự truyện",
    "tu tuong": "tư tưởng",
    "tu van": "tư vấn",
    "tuan le": "tuần lễ",
    "tuoi tac": "tuổi tác",
    "tuoi tre": "tuổi trẻ",
    "tuong lai": "tương lai",
    "tuong tu": "tương tự",
    "ung cu vien": "ứng cử viên",
    "ung ho": "ủng hộ",
    "uoc mo": "ước mơ",
    "uoc tinh": "ước tính",
    "vai tro": "vai trò",
    "van ban": "văn bản",
    "van de": "vấn đề",
    "van hoa": "văn hóa",
    "van phong": "văn phòng",
    "vat chat": "vật chất",
    "vat lieu": "vật liệu",
    "ve sinh": "vệ sinh",
    "vi du": "ví dụ",
    "vi tri": "vị trí",
    "vi truong": "vị trưởng",
    "viec lam": "việc làm",
    "vien thong": "viễn thông",
    "vong doi": "vòng đời",
    "vong quay": "vòng quay",
    "vuon hoa": "vườn hoa",
    "xa hoi": "xã hội",
    "xac dinh": "xác định",
    "xac nhan": "xác nhận",
    "xay dung": "xây dựng",
    "xem xet": "xem xét",
    "xin chao": "xin chào",
    "xu huong": "xu hướng",
    "xu ly": "xử lý",
    "xuat ban": "xuất bản",
    "xuat hien": "xuất hiện",
    "y kien": "ý kiến",
    "y nghia": "ý nghĩa",
    "y thuc": "ý thức",
    "y tuong": "ý tưởng",
    "yeu cau": "yêu cầu",
    "yeu thich": "yêu thích",
    "yeu to": "yếu tố",
}


def fix_vietnamese(text, mapping):
    """Fix Vietnamese text using mapping"""
    if text in mapping:
        return mapping[text]
    return text


def process_json(input_file, output_file):
    """Process JSON file and fix Vietnamese diacritics"""
    with open(input_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    fixed_count = 0
    
    for topic in data['topics']:
        # Fix topic name_vi
        old_name = topic.get('name_vi', '')
        new_name = fix_vietnamese(old_name, VIETNAMESE_MAPPING)
        if old_name != new_name:
            topic['name_vi'] = new_name
            fixed_count += 1
            print(f"Fixed topic: {old_name} -> {new_name}")
        
        # Fix word translations
        for word in topic.get('words', []):
            old_vi = word.get('vi', '')
            new_vi = fix_vietnamese(old_vi, VIETNAMESE_MAPPING)
            if old_vi != new_vi:
                word['vi'] = new_vi
                fixed_count += 1
    
    # Write output
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"\nTotal fixed: {fixed_count} entries")
    print(f"Output written to: {output_file}")


if __name__ == '__main__':
    import sys
    input_file = sys.argv[1] if len(sys.argv) > 1 else 'lib/data/german_vocabulary_by_topic.json'
    output_file = sys.argv[2] if len(sys.argv) > 2 else input_file
    process_json(input_file, output_file)
